### ISSUE TITLE
Как прошить данную прошивку напрямую в чип памяти без програматора

### ISSUE THREAD

**Issue by JerryLutor** [riftbit/RTD2660_PCB800099#2]
Как прошить данную прошивку напрямую в чип памяти ?

Оригинальный дамп микросхемы 25D40 - 512кб. А все прошивки 256кб. Что нужно изменить чтобы прошить?

**Comment by PC-maniak** [comment]
it is in order .. just delete the contents of the chip and upload the new firmware I just tested "PCB80009 pcb800100-ttl-480x272-4,3inch-at043tn24v.1-2av1vga-1hdmi-5key-ir2" and it works well
